#!/usr/bin/env ruby

:$.shift(File.expand_path(__FILE__))

require 'rubygems'
require 'stripe_email'
require 'mail'

mail_str = STDIN.read
mail = Mail.new(mail_str)

stripe_email_object = StripeEmail.new(mail, ARGV)
stripe_email_object.initialize_pad()
