#!/usr/bin/env ruby
Dir.chdir('/var/stripe/edits-benedict')

require 'rubygems'
require 'stripe_email'
require 'mail'

mail_str = STDIN.read
mail = Mail.new(mail_str)

stripe_email_object = StripeEmail.new(mail, ARGV)
stripe_email_object.initialize_pad()
